name: Typing


on:
  push:
    branches: [ "master", "dev" ]
    paths: [
      ".github/workflows/check-type.yml",
      "src/**.py",
      "src/**/py.typed",
      "tests/**.py",
      "requirements*.txt",
      "pyproject.toml",
    ]

  pull_request:
    branches: [ "master", "dev" ]
    paths: [
      ".github/workflows/check-type.yml",
      "src/**.py",
      "src/**/py.typed",
      "tests/**.py",
      "requirements*.txt",
      "pyproject.toml",
    ]

  workflow_dispatch:


jobs:
  type:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4.1.7

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5.1.0
        with:
          python-version: ${{ matrix.python-version }}
          check-latest: true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_cli.txt
          pip install -r requirements_dev.txt

      - name: Check with mypy
        run: mypy --enable-incomplete-feature=NewGenericSyntax

      - run: echo "🍏 This job's status is ${{ job.status }}."
