name: Testing


on:
  push:
    branches: [ "master", "dev" ]
    paths: [
      ".github/workflows/check-test.yml",
      "src/**.py",
      "tests/**",
      "requirements*.txt",
      "pyproject.toml",
    ]

  pull_request:
    branches: [ "master", "dev" ]
    paths: [
      ".github/workflows/check-test.yml",
      "src/**.py",
      "tests/**",
      "requirements*.txt",
      "pyproject.toml",
    ]

  schedule:
    - cron: "0 18 * * 5"

  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4.1.7

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5.1.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_cli.txt  # uses TokenManager (aiofiles)
          pip install -r requirements_dev.txt

      - name: Install the package
        run: pip install -e .

      - name: Test with pytest
        env:
          PYTEST_ADDOPTS: "--color=yes"
        run: pytest

      - run: echo "🍏 This job's status is ${{ job.status }}."
